# Generated by Django 4.0 on 2025-10-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0244_merge_20250912_1044'),
        ('management', '0245_alter_riskactionplan_likelihood'),
    ]

    operations = [
    ]
