# Generated by Django 4.0 on 2026-02-12 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0247_task_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskactionplan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted'),
        ),
    ]
