# Generated by Django 4.0 on 2026-03-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0248_riskactionplan_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='notify_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
