# Generated by Django 4.0 on 2026-03-12 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0249_alter_appointment_notify_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='notify_email',
        ),
    ]
