# Generated by Django 4.0 on 2026-03-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0250_remove_appointment_notify_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='notify_email',
            field=models.EmailField(blank=True, default='', max_length=254, null=True),
        ),
    ]
