# Generated by Django 4.0 on 2026-03-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0251_appointment_notify_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resident',
            name='ethnic_origin',
            field=models.CharField(blank=True, default='Unknown', max_length=30, null=True),
        ),
    ]
