# Generated by Django 4.0 on 2026-08-07 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0252_alter_resident_ethnic_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportplan',
            name='attachment',
        ),
    ]
