# Generated by Django 4.0 on 2026-08-07 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0253_remove_supportplan_attachment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supportplanfile',
            options={'ordering': ['-uploaded_date']},
        ),
        migrations.AddField(
            model_name='supportplanfile',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.user'),
        ),
    ]
