# Generated by Django 4.0 on 2026-08-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0254_alter_supportplanfile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resident',
            name='date_of_discharge',
            field=models.DateField(blank=True, null=True),
        ),
    ]
