# Generated by Django 4.0 on 2026-09-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0255_resident_date_of_discharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='category',
            field=models.CharField(choices=[('HousingTenancy', 'Housing/Tenancy'), ('FinanceMoneyBenefitManagement', 'Finance/Money/Benefit Management'), ('RentArrears', 'Rent Arrears'), ('Education', 'Education'), ('Training', 'Training'), ('Employment', 'Employment'), ('PhysicalHealth', 'Physical Health '), ('MentalHealthSubstanceUse', 'Mental Health/Substance Use'), ('LeisureSocialNetwork', 'LeisureSocial Network'), ('MovingOn', 'Moving On'), ('FurtherConcernsNeeds', 'Further Concerns/Needs'), ('ServicesProvidedByHousingOrEstateManagement', 'Services provided by Housing or Estate Management'), ('ServicesProvidedBySupportWorker', 'Services provided by support worker'), ("SupportWorker'sViewsofIssuesNeedsorActionsIfDifferentFromServiceUsers", "Support worker's views of issues, needs or Actions if different from service users")], max_length=100),
        ),
        migrations.AlterField(
            model_name='supportplan',
            name='title',
            field=models.CharField(choices=[('HousingTenancy', 'Housing/Tenancy'), ('FinanceMoneyBenefitManagement', 'Finance/Money/Benefit Management'), ('RentArrears', 'Rent Arrears'), ('Education', 'Education'), ('Training', 'Training'), ('Employment', 'Employment'), ('PhysicalHealth', 'Physical Health '), ('MentalHealthSubstanceUse', 'Mental Health/Substance Use'), ('LeisureSocialNetwork', 'LeisureSocial Network'), ('MovingOn', 'Moving On'), ('FurtherConcernsNeeds', 'Further Concerns/Needs'), ('ServicesProvidedByHousingOrEstateManagement', 'Services provided by Housing or Estate Management'), ('ServicesProvidedBySupportWorker', 'Services provided by support worker'), ("SupportWorker'sViewsofIssuesNeedsorActionsIfDifferentFromServiceUsers", "Support worker's views of issues, needs or Actions if different from service users")], default='None', max_length=100),
        ),
    ]
