# Generated by Django 4.0 on 2026-09-23 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0257_alter_supportplan_category_alter_supportplan_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_support_plans', to='management.user'),
        ),
    ]
