# Generated by Django 4.0 on 2026-09-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0258_supportplan_archived_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportplan',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
