# Generated by Django 4.0 on 2026-09-23 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0259_alter_supportplan_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportplan',
            name='keyworker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keyworker_support_plans', to='management.user'),
        ),
    ]
